name: Meetup-31-Jan-2023

on:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: Build
    # runs-on: ubuntu-20.04
    runs-on: # must meet all label requirements
      - self-hosted
      - meir-macbook-m1
    steps:
      - uses: actions/checkout@v3
      - name: Install Global Dependencies
        # Skip installing global dependencies on my (meir) machine
        if: ${{ !contains(runner.name, 'meir') }}
        run: make install-global-dependencies
      - name: Install dependencies
        run: make install-dependencies
      - name: Lint
        run: make lint
      - name: Build
        run: make build
